#!/usr/bin/env python3
"""
End‑to‑end driver to collect training data from a batch of TPTP FOF problems.

This script automates the following steps for each problem listed in a JSON
file (such as the one extracted from TPTP index pages):

1. Launch the external agent (EA) implemented in ``process_iprover_v3.py`` in
   interactive mode.  The EA listens on a chosen TCP port and assigns
   heuristic scores to candidate clauses using a dry‑run of the ranker,
   avoiding any calls to large language models.  The EA also logs all
   messages exchanged between iProver and the EA to a specified log file.

2. Run iProver in interactive mode on the given problem file, configured to
   talk to the EA via the chosen port.  iProver will send clause
   registration, passive/given/simplified events and, if a proof is found,
   the list of clauses that form the proof.  The EA uses the scores to
   guide the search.

3. When iProver terminates (either by finding a proof, giving up, or
   reaching a timeout), the EA also exits (thanks to the ``--exit-on-finish``
   flag).  We then parse the raw log generated by the EA to extract clause
   labels (positive/negative) using the helper in ``iplog_to_dataset.py``.

4. Append the labeled examples to a cumulative JSONL output file.  Each
   example includes the problem name, the clause id, basic id, textual
   representation, clause features, the binary label, and a fine‑grained
   negative bucket when applicable.

**Port management**
```````````````````
Because both iProver and the EA communicate over a TCP socket, this script
reserves a free port for each problem by binding a temporary socket.  This
avoids conflicts when running multiple problems in sequence.  After the
reservation, the socket is closed and the chosen port is passed to both
processes.

**Usage example**::

    python run_batch_pipeline.py \
        --problems fof_problems_from_html.json \
        --iprover iproveropt \
        --output dataset.jsonl \
        --limit 10 

Note that this script assumes that ``iproveropt`` (or ``iprover``) is in
your PATH.  On systems where iProver is not installed, the call will
fail; in that case you can still use the helper ``iplog_to_dataset.py``
directly on previously collected logs.
"""

import argparse
import json
import os
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import List, Dict, Any, Optional

# We will write entries about failed runs to a separate JSONL file.  To
# facilitate this, we provide a few small helper functions below.  If
# failures should be ignored, these functions will not be invoked.

def _append_jsonl(path: str, obj: dict) -> None:
    """Append a single JSON object to a JSONL file.

    Ensures the directory exists before writing.  The object is serialized
    using UTF‑8 and ascii preservation is disabled to allow non‑ASCII
    clause text in logs.  A newline is appended after each JSON record.
    """
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")


def extract_last_given(log_path: str, limit: int = 32) -> List[int]:
    """Extract the last few given_clause IDs from a raw log.

    When a run fails to produce a proof, it can be helpful to inspect the
    clauses that were most recently selected as "given".  This function
    parses the raw log in reverse, collecting up to ``limit`` clause
    identifiers from the final given_clause events.  If the log cannot be
    read or contains no such events, an empty list is returned.
    """
    if not os.path.exists(log_path):
        return []
    try:
        with open(log_path, "rb") as f:
            data = f.read()
        # split on NUL; iterate segments from the end
        parts = [seg for seg in data.split(b"\x00") if seg.strip()]
        last_ids: List[int] = []
        for segment in reversed(parts):
            for line in reversed(segment.splitlines()):
                line = line.strip()
                if not line:
                    continue
                try:
                    msg = json.loads(line.decode("utf-8", errors="ignore"))
                except Exception:
                    continue
                if msg.get("tag") == "given_clause":
                    for cid in msg.get("clause_ids", []) or []:
                        try:
                            last_ids.append(int(cid))
                        except Exception:
                            pass
                    if len(last_ids) >= limit:
                        break
            if len(last_ids) >= limit:
                break
        # We reversed segments and lines, so the collected IDs are newest first.
        return list(reversed(last_ids[-limit:]))
    except Exception:
        return []


def log_failure(
    fail_log_path: str,
    *,
    problem_name: str,
    file_path: str,
    domain: Optional[str],
    reason: str,
    timeout_sec: Optional[int],
    elapsed_sec: Optional[float],
    iprover_exit: Optional[int],
    external_port: Optional[int],
    log_path: Optional[str],
) -> None:
    """Record a failed problem run to a JSONL file.

    Each failure entry includes identifying information about the problem,
    the reason for failure ("timeout", "iprover_error", or "no_proof"),
    timing information, the external port used, the path to the raw log,
    and a timestamp.  To aid manual triage, the last few given clause IDs
    (if any) are extracted and included.  The function writes one line
    per failure to ``fail_log_path``.
    """
    entry: Dict[str, Any] = {
        "problem_name": problem_name,
        "file_path": file_path,
        "domain": domain,
        "reason": reason,
        "timeout_sec": timeout_sec,
        "elapsed_sec": elapsed_sec,
        "iprover_exit": iprover_exit,
        "external_port": external_port,
        "log_path": log_path,
        "timestamp": int(time.time()),
        "note": "manual_proof_needed",
    }
    # Attach recent given_clause IDs to help locate promising negatives
    if log_path:
        entry["last_given_ids"] = extract_last_given(log_path, limit=32)
    else:
        entry["last_given_ids"] = []
    _append_jsonl(fail_log_path, entry)


def has_proof_out(path: str) -> bool:
    """Check if the raw log contains a proof_out event.

    Since parsing the entire log as JSON can be expensive, we do a simple
    byte scan for the substring '"proof_out"'.  This is sufficient to
    detect whether a proof was emitted by iProver.  If the file does not
    exist, returns False.
    """
    if not os.path.exists(path):
        return False
    try:
        with open(path, "rb") as f:
            data = f.read()
        return b'"proof_out"' in data
    except Exception:
        return False

# Import helper functions for dataset generation.  We assume that
# iplog_to_dataset.py lives in the same directory as this script.  If you
# package these modules differently, adjust the import accordingly.
try:
    from iplog_to_dataset import parse_log, build_dataset
except Exception:
    # fall back to local import path
    sys.path.append(os.path.dirname(__file__))
    from iplog_to_dataset import parse_log, build_dataset


def find_free_port() -> int:
    """Return an available TCP port by binding a temporary socket."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(('127.0.0.1', 0))
        port = s.getsockname()[1]
    return port


def launch_ea(port: int, log_file: str, python_exec: str = sys.executable) -> subprocess.Popen:
    """Start the external agent (EA) server on the given port.

    Returns a ``subprocess.Popen`` object for the launched EA.  The EA
    command uses ``--dry-run`` to avoid calling the LLM and ``--exit-on-finish``
    so that it terminates once iProver finishes.
    """
    # Determine the absolute path of process_iprover_v3.py relative to this script
    here = Path(__file__).resolve().parent
    ea_script = here / 'process_iprover_v3.py'
    if not ea_script.exists():
        raise FileNotFoundError(f"Cannot locate process_iprover_v3.py at {ea_script}")
    cmd = [
        python_exec,
        str(ea_script),
        'serve',
        '--host', '127.0.0.1',
        '--port', str(port),
        '--dry-run',
        '--exit-on-finish',
        '--python-exec', '/home/ks/Proof-Guidance-for-Automated-Theorem-Proving-Using-Large-Language-Models/LLM/LLM_py311/bin/python',
        '--verbose', '--progress',
        '--log-file', log_file,
        # Use the heuristic scorer for dry-run; no LLM calls
        '--no-prefilter',
    ]
    # Launch EA; capture stdout/stderr for debugging if desired
    proc = subprocess.Popen(cmd, stdout=None, stderr=None)
    return proc


def launch_iprover(problem_path: str, port: int, iprover_bin: str, timeout: int = 300) -> subprocess.Popen:
    """Launch iProver in interactive mode for the given problem.

    This function constructs a command line that uses the passive scores
    mode (PSM) described in the iProver interactive README.  We enable
    superposition and instantiation components and disable resolution.  You
    may customise the flags further via the ``iprover_bin`` argument (e.g.
    pointing to ``iproveropt`` or ``iprover`` as appropriate).

    ``timeout`` specifies a hard time limit in seconds.  If exceeded,
    the subprocess will be killed by the caller.
    """
    # Construct the command for iProver.  See the README-interactive.md for
    # details on these flags.  The schedule is set to 'none' so that only
    # the external score governs clause selection.  Preprocessing is disabled
    # to speed up the run and avoid interfering with the learning task.
    cmd = [
        iprover_bin,
        '--interactive_mode', 'true',
        '--external_ip_address', '127.0.0.1',
        '--external_port', str(port),
        '--schedule', 'none',
        '--preprocessing_flag', 'false',
        '--instantiation_flag', 'true',
        '--superposition_flag', 'true',
        '--resolution_flag', 'false',
        '--sup_iter_deepening', '0',
        '--comb_sup_deep_mult', '0',
        '--sup_passive_queue_type', 'priority_queues',
        '--sup_passive_queues_freq', '[1]',
        '--sup_passive_queues', '[[+external_score]]',
        problem_path,
    ]
    # Start iProver process
    proc = subprocess.Popen(cmd, stdout=None, stderr=None)
    return proc


def collect_dataset_from_log(log_path: str, problem_name: str) -> List[Dict[str, Any]]:
    """Parse a raw log file and return a list of labeled clause entries."""
    clauses, proof_ids, seen = parse_log(log_path)
    return build_dataset(clauses, proof_ids, seen, problem_name=problem_name)


def run_problem(
    problem: Dict[str, Any],
    iprover_bin: str,
    output_dir: Path,
    cumulative_file: str,
    simulate: bool = False,
    timeout: int = 300,
    *,
    fail_log_path: Optional[str] = None,
    keep_failed_negatives: bool = False,
) -> None:
    """Run EA + iProver on a single problem and append results to the dataset.

    ``problem`` should contain at least ``problem_name`` and ``file_path``.
    ``iprover_bin`` is the executable to call.  ``output_dir`` is used to
    store per‑problem raw logs.  ``cumulative_file`` is the path to a
    JSONL file to which labelled examples are appended.

    If ``simulate`` is True, the iProver invocation is skipped and any
    existing log file is parsed instead.  This mode allows you to test
    the pipeline on pre‑collected logs without having iProver installed.
    """
    problem_name = problem.get('problem_name') or Path(problem.get('file_path')).stem
    problem_path = problem.get('file_path')
    log_file = output_dir / f"{problem_name}.raw.log"
    port = find_free_port()
    # Launch EA and optionally iProver.  Record start time to compute elapsed.
    ea_proc: Optional[subprocess.Popen] = None
    ip_proc: Optional[subprocess.Popen] = None
    start_time: float = time.time()
    failure_reason: Optional[str] = None
    iprover_exit: Optional[int] = None
    try:
        # Always start EA; even in simulate mode it will write an empty log.
        ea_proc = launch_ea(port, str(log_file))
        time.sleep(0.5)  # ensure EA is listening before starting iProver
        if not simulate:
            # Start iProver on the problem
            ip_proc = launch_iprover(problem_path, port, iprover_bin, timeout=timeout)
            try:
                # Wait for iProver to finish within the timeout
                iprover_exit = ip_proc.wait(timeout=timeout)
            except subprocess.TimeoutExpired:
                # Time limit exceeded: kill the process
                failure_reason = 'timeout'
                ip_proc.kill()
                ip_proc.wait()
        # Wait for EA to exit or force kill after a grace period
        try:
            ea_proc.wait(timeout=30)
        except subprocess.TimeoutExpired:
            if ea_proc:
                ea_proc.kill(); ea_proc.wait()
    finally:
        # Clean up any remaining child processes
        for p in (ip_proc, ea_proc):
            if p and p.poll() is None:
                p.kill(); p.wait()
    # 打印 iProver 错误输出（如果有）
    if failure_reason == 'iprover_error' and ip_proc is not None:
        print(f"[iprover_error] Problem: {problem_name}")
        # 由于 stdout/stderr 没有捕获，建议用户直接在终端查看详细输出。
        print(f"请在终端或 logs/{problem_name}.raw.log 查看详细错误信息。")
    # Determine failure conditions.  We only parse the log if
    #  1) a proof was found, OR
    #  2) keep_failed_negatives is True (to extract negatives) and a log exists.
    log_exists = log_file.exists()
    elapsed = time.time() - start_time
    # If iProver process ended (not simulate) with non-zero exit code and we haven't already classified as timeout
    if not simulate:
        if failure_reason is None and iprover_exit is not None and iprover_exit != 0:
            failure_reason = 'iprover_error'
        # If iProver exited normally (exit code 0) but there is no proof in the log, treat as no_proof
        if failure_reason is None and iprover_exit == 0:
            if not has_proof_out(str(log_file)):
                failure_reason = 'no_proof'
    # In simulate mode we cannot tell if there was a proof; treat missing proof
    if simulate:
        # If there is no proof_out in the existing log, mark as no_proof
        if not has_proof_out(str(log_file)):
            failure_reason = 'no_proof'
    # Log the failure if needed
    if failure_reason and fail_log_path:
        # Determine domain if provided in problem dict
        domain = problem.get('domain')
        log_failure(
            fail_log_path,
            problem_name=problem_name,
            file_path=problem_path,
            domain=domain,
            reason=failure_reason,
            timeout_sec=timeout if failure_reason == 'timeout' else None,
            elapsed_sec=elapsed,
            iprover_exit=iprover_exit if failure_reason == 'iprover_error' else (0 if failure_reason == 'no_proof' else None),
            external_port=port,
            log_path=str(log_file) if log_exists else None,
        )
    # Decide whether to parse dataset.  Only parse if there is a log and either
    # the run was successful (no failure) or keep_failed_negatives is True.
    if not log_exists:
        print(f"[warn] log file {log_file} was not created; skipping problem {problem_name}")
        return
    if failure_reason and not keep_failed_negatives:
        print(f"Skipped dataset generation for {problem_name} due to failure: {failure_reason}")
        return
    # Parse the raw log into dataset entries
    dataset_entries = collect_dataset_from_log(str(log_file), problem_name=problem_name)
    # Append to cumulative file
    with open(cumulative_file, 'a', encoding='utf-8') as out_fp:
        for row in dataset_entries:
            out_fp.write(json.dumps(row, ensure_ascii=False) + '\n')
    print(f"Processed {problem_name}: {len(dataset_entries)} clauses{' (failed run)' if failure_reason else ''}")


def main(argv: Optional[List[str]] = None) -> None:
    ap = argparse.ArgumentParser(description='Run iProver + EA over a list of problems to collect training data.')
    ap.add_argument('--problems', required=True, help='Path to JSON file containing problem list (as produced by fof_problems_from_html.json)')
    ap.add_argument('--iprover', default='/home/ks/iprover-master/iproveropt', help='Command or path to the iProver executable (iproveropt or iprover)')
    ap.add_argument('--output', required=True, help='Path to cumulative JSONL file to append labelled examples')
    ap.add_argument('--limit', type=int, default=None, help='Limit the number of problems to process (for testing)')
    ap.add_argument('--simulate', action='store_true', help='Do not run iProver; parse existing logs only')
    ap.add_argument('--timeout', type=int, default=300, help='Time limit in seconds for each iProver run')
    ap.add_argument('--fail-log', default='failed_problems.jsonl', help='Path to JSONL file for failed problems (timeout/iprover_error/no_proof)')
    ap.add_argument('--keep-failed-negatives', action='store_true',
                    help='If set, parse and include negative examples from runs that did not produce a proof; otherwise failed runs are logged and skipped')
    args = ap.parse_args(argv)

    # Load problem list
    with open(args.problems, 'r', encoding='utf-8') as f:
        data = json.load(f)
    if isinstance(data, list):
        problems = data
    elif 'problems' in data:
        problems = data['problems']
    else:
        raise ValueError('Could not determine problems list from JSON')
    # Prepare output directory for raw logs
    out_dir = Path(args.output).resolve().parent / 'logs'
    out_dir.mkdir(parents=True, exist_ok=True)
    # Ensure cumulative output file exists; if not, create empty
    cumulative_path = Path(args.output).resolve()
    if not cumulative_path.exists():
        cumulative_path.parent.mkdir(parents=True, exist_ok=True)
        cumulative_path.touch()
    # Iterate problems
    count = 0
    for prob in problems:
        if args.limit is not None and count >= args.limit:
            break
        run_problem(
            prob,
            iprover_bin=args.iprover,
            output_dir=out_dir,
            cumulative_file=str(cumulative_path),
            simulate=args.simulate,
            timeout=args.timeout,
            fail_log_path=args.fail_log,
            keep_failed_negatives=args.keep_failed_negatives,
        )
        count += 1
    print(f"Finished processing {count} problem(s)")


if __name__ == '__main__':
    main()